**Pandas** :

pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive.

In [7]:
import pandas as pd
import numpy as np
#datatypes:
#Series: one dimentional array

#Dataframe: two dimentional array

# Series

In [ ]:
#Series : one dimentional array

#create a series
s = pd.Series([1, 3, 5, np.nan, 6, 8])

#create a series with index
s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

#create serie from dictionary
s3 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})

#create series from numpy array
s4 = pd.Series(np.random.randn(5))

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
a    10
b    20
c    30
d    40
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
# DataFrames:table of series

# create a DataFrame from a dictionary of series
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

#create dataframe from list of lists
columns = ['Nom', 'Âge', 'Ville']
data_list = [
    ['Alice', 25, 'Paris'],
    ['Bob', 30, 'Lyon'],
    ['Charlie', 35, 'Marseille']
]

df2 = pd.DataFrame(data_list, columns=columns)

In [ ]:
#read csv file
pd.read_csv('data.csv')

#save to csv file
df.to_csv('data.csv', index=False)

#save to excel file
df.to_excel('data.xlsx', sheet_name='Sheet1', index=False)

In [ ]:
# access the data
df.head()

#access a column
df['Name']

#get the shape of the data
df.shape

#verify column names
df.columns

#verify data types
df.dtypes

#to get overview of the numerical data
df.describe()

#get technical info about the data
df.info()

In [ ]:
#to access a specific row
#using iloc(iloc means integer location)
df.iloc[0]

#using loc(loc means label)
df.loc['row_label']

#subset a dataframe
df['column_name']

#subset multiple columns
df[['column1', 'column2']]

#subset with conditions
df[df['column_name'] > value]

#subset multiple columns with one condition(a condition in on column)
df[df['column_name'] > value][['column1', 'column2']]

df.loc[df['column_name'] > value, ['column1', 'column2']]

#subset with iloc :select a range of rows and columns
df.iloc[9:25, 2:5]

In [ ]:
#to get unique values in a column
df[ 'column_name' ].unique()

#verify if there are null values
df[ 'column_name' ].notna() #notna() conditional function returns a True for each row the values are not a Null value

df[ 'column_name' ].isna() #isna() conditional function returns a True for each row the values are a Null value

#to count the number of null values in a column
df[ 'column_name' ].isna().sum()

In [10]:
# we will create a dataset of employees
np.random.seed(42)

data_complet = {
    'id': range(1, 101),
    'nom': [f'Employé_{i}' for i in range(1, 101)],
    'âge': np.random.randint(22, 65, 100),
    'département': np.random.choice(['IT', 'HR', 'Finance', 'Marketing', 'Operations'], 100),
    'salaire': np.random.normal(50000, 15000, 100).astype(int),
    'expérience': np.random.randint(1, 40, 100),
    'ville': np.random.choice(['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice'], 100),
    'performance': np.random.randint(1, 11, 100),
    'date_embauche': pd.date_range('2010-01-01', periods=100, freq='M'),
    'congés_restants': np.random.randint(0, 31, 100)
}

employees_df = pd.DataFrame(data_complet)

# Add some missing values to make it more realistic
employees_df.loc[10:15, 'salaire'] = np.nan
employees_df.loc[20:25, 'expérience'] = np.nan
employees_df.loc[5:8, 'performance'] = np.nan

/var/folders/62/qv7mlq7x6r10s2pmbxgzbpzh0000gn/T/ipykernel_34868/1692406485.py:13: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  'date_embauche': pd.date_range('2010-01-01', periods=100, freq='M'),

In [11]:
#get the shape of the dataset
employees_df.shape

(100, 10)

In [12]:
# get the first 5 rows
employees_df.head()

,id,nom,âge,département,salaire,expérience,ville,performance,date_embauche,congés_restants
0,1,Employé_1,60,IT,58802.0,22.0,Nice,4.0,2010-01-31,4
1,2,Employé_2,50,Marketing,82856.0,6.0,Lyon,4.0,2010-02-28,30
2,3,Employé_3,36,HR,35141.0,15.0,Lyon,6.0,2010-03-31,4
3,4,Employé_4,64,IT,41505.0,37.0,Lyon,3.0,2010-04-30,5
4,5,Employé_5,29,Operations,51494.0,33.0,Lyon,6.0,2010-05-31,2

In [13]:
# get the last 5 rows
employees_df.tail()

,id,nom,âge,département,salaire,expérience,ville,performance,date_embauche,congés_restants
95,96,Employé_96,26,Finance,51228.0,35.0,Nice,1.0,2017-12-31,27
96,97,Employé_97,63,IT,84719.0,23.0,Paris,5.0,2018-01-31,19
97,98,Employé_98,60,Operations,21991.0,17.0,Toulouse,7.0,2018-02-28,23
98,99,Employé_99,62,Marketing,60293.0,26.0,Paris,6.0,2018-03-31,4
99,100,Employé_100,49,HR,25809.0,8.0,Paris,1.0,2018-04-30,1

In [14]:
# get a random sample of 5 rows
employees_df.sample(5)

,id,nom,âge,département,salaire,expérience,ville,performance,date_embauche,congés_restants
70,71,Employé_71,44,IT,52597.0,4.0,Lyon,2.0,2015-11-30,14
97,98,Employé_98,60,Operations,21991.0,17.0,Toulouse,7.0,2018-02-28,23
89,90,Employé_90,32,HR,59770.0,10.0,Lyon,6.0,2017-06-30,3
19,20,Employé_20,51,HR,52769.0,28.0,Toulouse,9.0,2011-08-31,18
39,40,Employé_40,25,IT,37689.0,26.0,Paris,1.0,2013-04-30,17

In [15]:
#get the technical information about the data frame
employees_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               100 non-null    int64
 1   nom              100 non-null    object
 2   âge              100 non-null    int64
 3   département      100 non-null    object
 4   salaire          94 non-null     float64
 5   expérience       94 non-null     float64
 6   ville            100 non-null    object
 7   performance      96 non-null     float64
 8   date_embauche    100 non-null    datetime64[ns]
 9   congés_restants  100 non-null    int64
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 7.9+ KB

In [16]:
#get description of numeric columns
employees_df.describe()

,id,âge,salaire,expérience,performance,date_embauche,congés_restants
count,100.000000,100.000000,94.000000,94.000000,96.000000,100,100.000000
mean,50.500000,42.270000,51651.946809,20.489362,5.260417,2014-03-16 06:14:24,14.440000
min,1.000000,22.000000,21991.000000,1.000000,1.000000,2010-01-31 00:00:00,0.000000
25%,25.750000,31.750000,38840.750000,10.500000,3.000000,2012-02-21 18:00:00,5.000000
50%,50.500000,42.500000,53447.000000,22.000000,5.000000,2014-03-15 12:00:00,15.500000
75%,75.250000,51.250000,59673.750000,31.000000,8.000000,2016-04-07 12:00:00,22.000000
max,100.000000,64.000000,107790.000000,39.000000,10.000000,2018-04-30 00:00:00,30.000000
std,29.011492,12.335262,15167.447935,11.842828,2.928067,NaN,9.447698

In [18]:
#verify the data types of the columns
employees_df.dtypes

id                          int64
nom                        object
âge                         int64
département                object
salaire                   float64
expérience                float64
ville                      object
performance               float64
date_embauche      datetime64[ns]
congés_restants             int64
dtype: object

In [19]:
#verify if there are any missing values
employees_df.isnull().sum()

id                 0
nom                0
âge                0
département        0
salaire            6
expérience         6
ville              0
performance        4
date_embauche      0
congés_restants    0
dtype: int64

In [20]:
#verify if there are any duplicate rows
employees_df.duplicated().sum()

np.int64(0)

In [21]:
#get the columns of the data frame
employees_df.columns

Index(['id', 'nom', 'âge', 'département', 'salaire', 'expérience', 'ville',
       'performance', 'date_embauche', 'congés_restants'],
      dtype='object')

In [ ]:
#separate categorical and numeric columns
numerical_data=employees_df.select_dtypes(include=[np.number])
categorical_data=employees_df.select_dtypes(exclude=[np.number])
date_data=employees_df.select_dtypes(include=[np.datetime64])

In [22]:
#access a specific column
employees_df['nom']

0       Employé_1
1       Employé_2
2       Employé_3
3       Employé_4
4       Employé_5
         ...
95     Employé_96
96     Employé_97
97     Employé_98
98     Employé_99
99    Employé_100
Name: nom, Length: 100, dtype: object

In [23]:
#access many columns
employees_df[['nom','âge','ville']]

            nom  âge     ville
0     Employé_1   60      Nice
1     Employé_2   50      Lyon
2     Employé_3   36      Lyon
3     Employé_4   64      Lyon
4     Employé_5   29      Lyon
..          ...  ...       ...
95   Employé_96   26      Nice
96   Employé_97   63     Paris
97   Employé_98   60  Toulouse
98   Employé_99   62     Paris
99  Employé_100   49     Paris

[100 rows x 3 columns]

In [24]:
#slice rows 
employees_df.iloc[5:10]

,id,nom,âge,département,salaire,expérience,ville,performance,date_embauche,congés_restants
5,6,Employé_6,42,Finance,42447.0,8.0,Marseille,NaN,2010-06-30,20
6,7,Employé_7,60,Marketing,26740.0,5.0,Paris,NaN,2010-07-31,22
7,8,Employé_8,40,Finance,51028.0,39.0,Toulouse,NaN,2010-08-31,4
8,9,Employé_9,44,Finance,34065.0,4.0,Lyon,NaN,2010-09-30,20
9,10,Employé_10,32,IT,57103.0,6.0,Nice,7.0,2010-10-31,4

In [25]:

employees_df.loc[5:10]

,id,nom,âge,département,salaire,expérience,ville,performance,date_embauche,congés_restants
5,6,Employé_6,42,Finance,42447.0,8.0,Marseille,NaN,2010-06-30,20
6,7,Employé_7,60,Marketing,26740.0,5.0,Paris,NaN,2010-07-31,22
7,8,Employé_8,40,Finance,51028.0,39.0,Toulouse,NaN,2010-08-31,4
8,9,Employé_9,44,Finance,34065.0,4.0,Lyon,NaN,2010-09-30,20
9,10,Employé_10,32,IT,57103.0,6.0,Nice,7.0,2010-10-31,4
10,11,Employé_11,32,Finance,NaN,32.0,Lyon,3.0,2010-11-30,9

In [26]:
#filter data
employees_df[employees_df['âge']>30]

,id,nom,âge,département,salaire,expérience,ville,performance,date_embauche,congés_restants
0,1,Employé_1,60,IT,58802.0,22.0,Nice,4.0,2010-01-31,4
1,2,Employé_2,50,Marketing,82856.0,6.0,Lyon,4.0,2010-02-28,30
2,3,Employé_3,36,HR,35141.0,15.0,Lyon,6.0,2010-03-31,4
3,4,Employé_4,64,IT,41505.0,37.0,Lyon,3.0,2010-04-30,5
5,6,Employé_6,42,Finance,42447.0,8.0,Marseille,NaN,2010-06-30,20
...,...,...,...,...,...,...,...,...,...,...
94,95,Employé_95,54,Finance,42719.0,2.0,Marseille,3.0,2017-11-30,16
96,97,Employé_97,63,IT,84719.0,23.0,Paris,5.0,2018-01-31,19
97,98,Employé_98,60,Operations,21991.0,17.0,Toulouse,7.0,2018-02-28,23
98,99,Employé_99,62,Marketing,60293.0,26.0,Paris,6.0,2018-03-31,4
99,100,Employé_100,49,HR,25809.0,8.0,Paris,1.0,2018-04-30,1

In [27]:
employees_df[employees_df.âge >30]

,id,nom,âge,département,salaire,expérience,ville,performance,date_embauche,congés_restants
0,1,Employé_1,60,IT,58802.0,22.0,Nice,4.0,2010-01-31,4
1,2,Employé_2,50,Marketing,82856.0,6.0,Lyon,4.0,2010-02-28,30
2,3,Employé_3,36,HR,35141.0,15.0,Lyon,6.0,2010-03-31,4
3,4,Employé_4,64,IT,41505.0,37.0,Lyon,3.0,2010-04-30,5
5,6,Employé_6,42,Finance,42447.0,8.0,Marseille,NaN,2010-06-30,20
...,...,...,...,...,...,...,...,...,...,...
94,95,Employé_95,54,Finance,42719.0,2.0,Marseille,3.0,2017-11-30,16
96,97,Employé_97,63,IT,84719.0,23.0,Paris,5.0,2018-01-31,19
97,98,Employé_98,60,Operations,21991.0,17.0,Toulouse,7.0,2018-02-28,23
98,99,Employé_99,62,Marketing,60293.0,26.0,Paris,6.0,2018-03-31,4
99,100,Employé_100,49,HR,25809.0,8.0,Paris,1.0,2018-04-30,1

In [29]:
#deal with duplicates
employees_df.drop_duplicates()

#fill missing values
employees_df.fillna(employees_df.mean,inplace=True) #fill missing walues with its mean

/var/folders/62/qv7mlq7x6r10s2pmbxgzbpzh0000gn/T/ipykernel_34868/3689805576.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method DataFrame.mean of      id          nom  âge département  salaire  expérience     ville  \
0     1    Employé_1   60          IT  58802.0        22.0      Nice
1     2    Employé_2   50   Marketing  82856.0         6.0      Lyon
2     3    Employé_3   36          HR  35141.0        15.0      Lyon
3     4    Employé_4   64          IT  41505.0        37.0      Lyon
4     5    Employé_5   29  Operations  51494.0        33.0      Lyon
..  ...          ...  ...         ...      ...         ...       ...
95   96   Employé_96   26     Finance  51228.0        35.0      Nice
96   97   Employé_97   63          IT  84719.0        23.0     Paris
97   98   Employé_98   60  Operations  21991.0        17.0  Toulouse
98   99   Employé_99   62   Marketing  60293.0        26.0     Paris
99  100  Employé_100   49          HR  25809.0         8.0     Paris

    performance date_embauche  congés_restants
0           4.0    2010-01-31                4
1           4.0    2010-02-28               30
2           6.0    2010-03-31                4
3           3.0    2010-04-30                5
4           6.0    2010-05-31                2
..          ...           ...              ...
95          1.0    2017-12-31               27
96          5.0    2018-01-31               19
97          7.0    2018-02-28               23
98          6.0    2018-03-31                4
99          1.0    2018-04-30                1

[100 rows x 10 columns]>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  employees_df.fillna(employees_df.mean,inplace=True) #fill missing walues with its mean
/var/folders/62/qv7mlq7x6r10s2pmbxgzbpzh0000gn/T/ipykernel_34868/3689805576.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method DataFrame.mean of      id          nom  âge département  salaire  expérience     ville  \
0     1    Employé_1   60          IT  58802.0        22.0      Nice
1     2    Employé_2   50   Marketing  82856.0         6.0      Lyon
2     3    Employé_3   36          HR  35141.0        15.0      Lyon
3     4    Employé_4   64          IT  41505.0        37.0      Lyon
4     5    Employé_5   29  Operations  51494.0        33.0      Lyon
..  ...          ...  ...         ...      ...         ...       ...
95   96   Employé_96   26     Finance  51228.0        35.0      Nice
96   97   Employé_97   63          IT  84719.0        23.0     Paris
97   98   Employé_98   60  Operations  21991.0        17.0  Toulouse
98   99   Employé_99   62   Marketing  60293.0        26.0     Paris
99  100  Employé_100   49          HR  25809.0         8.0     Paris

    performance date_embauche  congés_restants
0           4.0    2010-01-31                4
1           4.0    2010-02-28               30
2           6.0    2010-03-31                4
3           3.0    2010-04-30                5
4           6.0    2010-05-31                2
..          ...           ...              ...
95          1.0    2017-12-31               27
96          5.0    2018-01-31               19
97          7.0    2018-02-28               23
98          6.0    2018-03-31                4
99          1.0    2018-04-30                1

[100 rows x 10 columns]>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  employees_df.fillna(employees_df.mean,inplace=True) #fill missing walues with its mean
/var/folders/62/qv7mlq7x6r10s2pmbxgzbpzh0000gn/T/ipykernel_34868/3689805576.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method DataFrame.mean of      id          nom  âge département  salaire  expérience     ville  \
0     1    Employé_1   60          IT  58802.0        22.0      Nice
1     2    Employé_2   50   Marketing  82856.0         6.0      Lyon
2     3    Employé_3   36          HR  35141.0        15.0      Lyon
3     4    Employé_4   64          IT  41505.0        37.0      Lyon
4     5    Employé_5   29  Operations  51494.0        33.0      Lyon
..  ...          ...  ...         ...      ...         ...       ...
95   96   Employé_96   26     Finance  51228.0        35.0      Nice
96   97   Employé_97   63          IT  84719.0        23.0     Paris
97   98   Employé_98   60  Operations  21991.0        17.0  Toulouse
98   99   Employé_99   62   Marketing  60293.0        26.0     Paris
99  100  Employé_100   49          HR  25809.0         8.0     Paris

    performance date_embauche  congés_restants
0           4.0    2010-01-31                4
1           4.0    2010-02-28               30
2           6.0    2010-03-31                4
3           3.0    2010-04-30                5
4           6.0    2010-05-31                2
..          ...           ...              ...
95          1.0    2017-12-31               27
96          5.0    2018-01-31               19
97          7.0    2018-02-28               23
98          6.0    2018-03-31                4
99          1.0    2018-04-30                1

[100 rows x 10 columns]>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  employees_df.fillna(employees_df.mean,inplace=True) #fill missing walues with its mean

In [30]:
#delete missing values
employees_df.dropna()

,id,nom,âge,département,salaire,expérience,ville,performance,date_embauche,congés_restants
0,1,Employé_1,60,IT,58802.0,22.0,Nice,4.0,2010-01-31,4
1,2,Employé_2,50,Marketing,82856.0,6.0,Lyon,4.0,2010-02-28,30
2,3,Employé_3,36,HR,35141.0,15.0,Lyon,6.0,2010-03-31,4
3,4,Employé_4,64,IT,41505.0,37.0,Lyon,3.0,2010-04-30,5
4,5,Employé_5,29,Operations,51494.0,33.0,Lyon,6.0,2010-05-31,2
...,...,...,...,...,...,...,...,...,...,...
95,96,Employé_96,26,Finance,51228.0,35.0,Nice,1.0,2017-12-31,27
96,97,Employé_97,63,IT,84719.0,23.0,Paris,5.0,2018-01-31,19
97,98,Employé_98,60,Operations,21991.0,17.0,Toulouse,7.0,2018-02-28,23
98,99,Employé_99,62,Marketing,60293.0,26.0,Paris,6.0,2018-03-31,4
99,100,Employé_100,49,HR,25809.0,8.0,Paris,1.0,2018-04-30,1

In [31]:
#rename columns
employees_df.rename(columns={'nom':'name'},inplace=True)

In [41]:
#create a subset 
old_employees = employees_df.loc[employees_df['âge'] > 30, 
                               ['name', 'département','âge', 'expérience', 'performance', 'date_embauche']]

In [42]:
#take a copy 
employees_df_copy = employees_df.copy()

In [ ]:
#apply a function
def set_age_category(age):
    if age < 30:
        return 'jeune'
    elif age < 50:
        return 'moyen'
    else:
        return 'vieux'

employees_df_copy['âge_categorie'] = employees_df_copy['âge'].apply(set_age_category)
#using pd.cut:cut the data into bins
employees_df['âge_categorie'] = pd.cut(employees_df['âge'], bins=[0, 30, 50, 100], labels=['jeune', 'moyen', 'vieux'])
# using pd.qcut:cut thedata into quantiles
employees_df['âge_categorie'] = pd.qcut(employees_df['âge'], q=3, labels=['jeune', 'moyen', 'vieux'])

In [57]:
#aggregation :to calculate the average performance of employees
employees_df.groupby('département')['âge'].mean()

département
Finance       43.285714
HR            42.800000
IT            43.880000
Marketing     39.727273
Operations    41.470588
Name: âge, dtype: float64

In [56]:
employees_df.groupby(['département','ville'])['âge'].agg(['mean', 'max', 'min'])

                            mean  max  min
département ville
Finance     Lyon       37.333333   44   32
            Marseille  47.428571   61   28
            Nice       43.800000   52   26
            Paris      50.000000   58   42
            Toulouse   32.000000   40   25
HR          Lyon       34.000000   36   32
            Marseille  39.000000   39   39
            Nice       50.500000   61   28
            Paris      40.285714   60   24
            Toulouse   51.000000   51   51
IT          Lyon       42.000000   64   25
            Marseille  58.500000   63   54
            Nice       44.500000   61   23
            Paris      41.400000   63   22
            Toulouse   42.400000   57   22
Marketing   Lyon       46.000000   59   29
            Marseille  34.000000   42   29
            Nice       35.000000   56   23
            Paris      45.000000   62   33
            Toulouse   36.666667   46   23
Operations  Lyon       40.000000   48   29
            Marseille  45.000000   47   43
            Nice       33.000000   46   23
            Paris      63.000000   63   63
            Toulouse   45.400000   60   37

In [64]:
#aggregation multiple colonnes
agg_gen=employees_df.groupby('département').agg(
    {'salaire':lambda x: pd.to_numeric(x, errors='coerce').mean() ,
    'âge':lambda x: pd.to_numeric(x, errors='coerce').mean(),
    'expérience':lambda x: pd.to_numeric(x, errors='coerce').mean()
    }
).rename(columns={'salaire':'moy_salaire', 'âge':'moy_âge', 'expérience':'moy_expérience'})

In [65]:
agg_gen

              moy_salaire    moy_âge  moy_expérience
département
Finance      45652.842105  43.285714       23.100000
HR           45150.785714  42.800000       19.933333
IT           53504.416667  43.880000       20.750000
Marketing    54146.590909  39.727273       18.200000
Operations   58695.800000  41.470588       20.200000

In [66]:
#merge dataframes:merging is like to join tables in sql
clients_data = {
    'client_id': [1, 2, 3, 4, 5],
    'nom': ['Alice Dupont', 'Bob Martin', 'Charlie Brown', 'Diana Prince', 'Eve Smith'],
    'ville': ['Paris', 'Lyon', 'Marseille', 'Paris', 'Lyon'],
    'date_inscription': ['2023-01-15', '2023-02-20', '2023-01-10', '2023-03-05', '2023-02-28']
}

transactions_data = {
    'transaction_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'client_id': [1, 1, 2, 3, 1, 4, 2, 3, 5, 1],
    'montant': [150, 200, 75, 300, 50, 120, 180, 90, 250, 100],
    'date_transaction': ['2023-02-01', '2023-03-15', '2023-02-28', '2023-03-10', 
                        '2023-04-01', '2023-03-20', '2023-04-15', '2023-05-01',
                        '2023-04-10', '2023-05-20']
}
clients_df = pd.DataFrame(clients_data)
transactions_df = pd.DataFrame(transactions_data)

#inner join :to keep only the rows that have a match in both dataframes
inner_join = pd.merge(clients_df, transactions_df, on='client_id', how='inner')
print(inner_join)

#left join :to keep all the rows from the left dataframe and the matching rows from the right dataframe
left_join = pd.merge(clients_df, transactions_df, on='client_id', how='left')
print(left_join)

#right join :to keep all the rows from the right dataframe and the matching rows from the left dataframe
right_join = pd.merge(clients_df, transactions_df, on='client_id', how='right')
print(right_join)

#outer join :to keep all the rows from both dataframes
outer_join = pd.merge(clients_df, transactions_df, on='client_id', how='outer')
print(outer_join)

   client_id            nom      ville date_inscription  transaction_id  \
0          1   Alice Dupont      Paris       2023-01-15             101
1          1   Alice Dupont      Paris       2023-01-15             102
2          1   Alice Dupont      Paris       2023-01-15             105
3          1   Alice Dupont      Paris       2023-01-15             110
4          2     Bob Martin       Lyon       2023-02-20             103
5          2     Bob Martin       Lyon       2023-02-20             107
6          3  Charlie Brown  Marseille       2023-01-10             104
7          3  Charlie Brown  Marseille       2023-01-10             108
8          4   Diana Prince      Paris       2023-03-05             106
9          5      Eve Smith       Lyon       2023-02-28             109

   montant date_transaction
0      150       2023-02-01
1      200       2023-03-15
2       50       2023-04-01
3      100       2023-05-20
4       75       2023-02-28
5      180       2023-04-15
6      300       2023-03-10
7       90       2023-05-01
8      120       2023-03-20
9      250       2023-04-10
   client_id            nom      ville date_inscription  transaction_id  \
0          1   Alice Dupont      Paris       2023-01-15             101
1          1   Alice Dupont      Paris       2023-01-15             102
2          1   Alice Dupont      Paris       2023-01-15             105
3          1   Alice Dupont      Paris       2023-01-15             110
4          2     Bob Martin       Lyon       2023-02-20             103
5          2     Bob Martin       Lyon       2023-02-20             107
6          3  Charlie Brown  Marseille       2023-01-10             104
7          3  Charlie Brown  Marseille       2023-01-10             108
8          4   Diana Prince      Paris       2023-03-05             106
9          5      Eve Smith       Lyon       2023-02-28             109

   montant date_transaction
0      150       2023-02-01
1      200       2023-03-15
2       50       2023-04-01
3      100       2023-05-20
4       75       2023-02-28
5      180       2023-04-15
6      300       2023-03-10
7       90       2023-05-01
8      120       2023-03-20
9      250       2023-04-10
   client_id            nom      ville date_inscription  transaction_id  \
0          1   Alice Dupont      Paris       2023-01-15             101
1          1   Alice Dupont      Paris       2023-01-15             102
2          2     Bob Martin       Lyon       2023-02-20             103
3          3  Charlie Brown  Marseille       2023-01-10             104
4          1   Alice Dupont      Paris       2023-01-15             105
5          4   Diana Prince      Paris       2023-03-05             106
6          2     Bob Martin       Lyon       2023-02-20             107
7          3  Charlie Brown  Marseille       2023-01-10             108
8          5      Eve Smith       Lyon       2023-02-28             109
9          1   Alice Dupont      Paris       2023-01-15             110

   montant date_transaction
0      150       2023-02-01
1      200       2023-03-15
2       75       2023-02-28
3      300       2023-03-10
4       50       2023-04-01
5      120       2023-03-20
6      180       2023-04-15
7       90       2023-05-01
8      250       2023-04-10
9      100       2023-05-20
   client_id            nom      ville date_inscription  transaction_id  \
0          1   Alice Dupont      Paris       2023-01-15             101
1          1   Alice Dupont      Paris       2023-01-15             102
2          1   Alice Dupont      Paris       2023-01-15             105
3          1   Alice Dupont      Paris       2023-01-15             110
4          2     Bob Martin       Lyon       2023-02-20             103
5          2     Bob Martin       Lyon       2023-02-20             107
6          3  Charlie Brown  Marseille       2023-01-10             104
7          3  Charlie Brown  Marseille       2023-01-10             108
8          4   Diana Prince      Paris       2023-03-05             106
9          5      Eve Smith       Lyon       2023-02-28             109

   montant date_transaction
0      150       2023-02-01
1      200       2023-03-15
2       50       2023-04-01
3      100       2023-05-20
4       75       2023-02-28
5      180       2023-04-15
6      300       2023-03-10
7       90       2023-05-01
8      120       2023-03-20
9      250       2023-04-10

In [72]:
#deal with date

#convert to datetime
employees_df['date_embauche']=pd.to_datetime(employees_df['date_embauche'])

#extract year
employees_df['annee_embauche']=employees_df['date_embauche'].dt.year

#extract month
employees_df['mois_embauche']=employees_df['date_embauche'].dt.month

#extract day
employees_df['jour_embauche']=employees_df['date_embauche'].dt.day

#extract day of week
employees_df['jour_semaine_embauche']=employees_df['date_embauche'].dt.dayofweek

In [74]:
employees_df

,id,name,âge,département,salaire,expérience,ville,performance,date_embauche,congés_restants,âge_categorie,annee_embauche,mois_embauche,jour_embauche,jour_semaine_embauche
0,1,Employé_1,60,IT,58802.0,22.0,Nice,4.0,2010-01-31,4,vieux,2010,1,31,6
1,2,Employé_2,50,Marketing,82856.0,6.0,Lyon,4.0,2010-02-28,30,moyen,2010,2,28,6
2,3,Employé_3,36,HR,35141.0,15.0,Lyon,6.0,2010-03-31,4,moyen,2010,3,31,2
3,4,Employé_4,64,IT,41505.0,37.0,Lyon,3.0,2010-04-30,5,vieux,2010,4,30,4
4,5,Employé_5,29,Operations,51494.0,33.0,Lyon,6.0,2010-05-31,2,jeune,2010,5,31,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Employé_96,26,Finance,51228.0,35.0,Nice,1.0,2017-12-31,27,jeune,2017,12,31,6
96,97,Employé_97,63,IT,84719.0,23.0,Paris,5.0,2018-01-31,19,vieux,2018,1,31,2
97,98,Employé_98,60,Operations,21991.0,17.0,Toulouse,7.0,2018-02-28,23,vieux,2018,2,28,2
98,99,Employé_99,62,Marketing,60293.0,26.0,Paris,6.0,2018-03-31,4,vieux,2018,3,31,5
99,100,Employé_100,49,HR,25809.0,8.0,Paris,1.0,2018-04-30,1,moyen,2018,4,30,0